# -*- coding: utf-8 -*-
"""Program5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19EngMoFvZ2DbM-T1t5-jlTnV5anRFmXz
"""



"""Matrix vector equation"""

import numpy as np
A = np.array([[2, 1,-2],[3,0,1],[1,1,-1]])
b = np.array([-3,5,-2])
X = np.linalg.solve(A, b)
print("Matrix A:")
print(A)
print("Vector b:")
print(b)
print("Solution for X:")
print(X)