# -*- coding: utf-8 -*-
"""Program1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UPAF8MbuNk6G88Ju1uQflXo4TUZ_9HzM
"""

Basic Array Creation

import numpy as np
array_from_list=np.array([1,2,3,4,5])
print("array from list:",array_from_list)

"""creating an array with a range of values"""

array_with_range=np.arange(10)
print("Array with range:",array_with_range)

"""Creating an array of zeros"""

zeros_array=np.zeros((3,3))
print("Array of zeros:\n",zeros_array)

"""Creating an array of ones"""

import numpy as np
ones_array=np.ones((2,5))
print("Array of ones:\n",ones_array)